# Generated by Django 4.2.7 on 2023-11-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='role',
            field=models.TextField(default='ai'),
        ),
    ]
