# Generated by Django 4.2.7 on 2023-11-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chatbot_answer',
            field=models.TextField(null=True),
        ),
    ]
