# Generated by Django 4.2.7 on 2023-11-15 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_message_chatbot_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chatbot_answer',
        ),
        migrations.AddField(
            model_name='message',
            name='previous_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='message.message'),
        ),
    ]
