# Generated by Django 4.2.7 on 2023-11-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_remove_message_chatbot_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='parameters',
            field=models.TextField(blank=True, null=True),
        ),
    ]
