# Generated by Django 4.2.7 on 2023-11-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_message_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='draw',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='', verbose_name='draw'),
        ),
    ]
