# Generated by Django 4.2.7 on 2024-02-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_message_draw'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_code',
            field=models.BooleanField(default=True),
        ),
    ]
