# Generated by Django 4.2.7 on 2024-02-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_alter_message_is_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_code',
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('code', 'code'), ('button', 'button')], default='text', max_length=20),
        ),
    ]
