# Generated by Django 4.2.7 on 2024-02-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_remove_message_is_code_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('code', 'code'), ('parameters', 'parameters')], default='text', max_length=20),
        ),
    ]
