# Generated by Django 4.2.7 on 2024-03-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_message_is_solved_alter_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='needs_button',
            field=models.BooleanField(default=False),
        ),
    ]
