version: '3.9'


services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    volumes:
      - ./frontend:/app/frontend

    depends_on:
      - backend

  db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    volumes:
      - ./data/db:/var/lib/postgresql/data/

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    ports:
      - '8000:8000'

    volumes:
      - ./backend:/app/backend
      - static-files:/app/backend/static-files
      - media-files:/app/backend/media-files

    depends_on:
      - db

#  nginx:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    volumes:
#      - static-files:/static-files
#      - media-files:/media-files
#    ports:
#      - "80:80"
#    depends_on:
#      - backend

volumes:
  db:
  static-files:
  media-files:
