name: C4Qenv
dependencies:
  - python=3.11.4
  - psycopg2=2.9.3
  - pip=23.3
  - pip:
      - flake8==6.0.0
      - transformers==4.31.0
#      - qiskit_algorithms==0.3.0
      - qiskit_algorithms
      - qiskit==1.0.1
#      - qiskit_optimization==0.6.1
      - qiskit_optimization
      - numpy==1.26.4
      - networkx==3.2.1
      - matplotlib==3.8.2
      - datasets==2.16.1
      - evaluate==0.4.1
      - transformers[torch]==4.31.0
      - torch==2.2.2
      - scikit-learn==1.3.0
      - pytest==8.0.0
      - tabulate==0.9.0
      - tqdm==4.65.0
      - pandas==2.0.3
      - 'qiskit[visualization]'
      - tensorflow==2.16.1
      - transformers-interpret==0.10.0
      - simpletransformers==0.64.3
      - django==4.2.7
      - djangorestframework==3.14.0
      - djangorestframework_simplejwt==5.3.0
      - drf_yasg==1.21.7
      - pillow==10.1.0
      - django-cors-headers==4.3.0
      - psycopg2-binary==2.9.9
      - django-cleanup==8.0.0
      - gunicorn==21.2.0
      - selenium==4.18.1
      - requests==2.31.0